/**
 * Demo Seed Data - Sample Customers/Entities
 *
 * Pre-configured customer profiles for demonstrations.
 */

import type { ArkaEntity } from '@arka-protocol/types';

/**
 * Individual customers
 */
export const individualCustomers: ArkaEntity[] = [
  {
    id: 'ent_cust_001',
    type: 'Customer',
    data: {
      customerId: 'cust_001',
      customerType: 'INDIVIDUAL',
      firstName: 'John',
      lastName: 'Smith',
      email: 'john.smith@example.com',
      phone: '+1-555-0101',
      dateOfBirth: '1985-03-15',
      ssn: '***-**-1234',
      kycStatus: 'VERIFIED',
      kycVerifiedAt: '2023-01-15T10:00:00Z',
      riskLevel: 'LOW',
      riskScore: 15,
      isPEP: false,
      address: {
        street: '123 Main Street',
        city: 'San Francisco',
        state: 'CA',
        zip: '94102',
        country: 'US',
      },
      occupation: 'Software Engineer',
      annualIncome: 150000,
      sourceOfFunds: 'EMPLOYMENT',
      accountOpenDate: '2022-01-10',
      accountAgeDays: 730,
    },
    createdAt: '2022-01-10T10:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ent_cust_002',
    type: 'Customer',
    data: {
      customerId: 'cust_002',
      customerType: 'INDIVIDUAL',
      firstName: 'Jane',
      lastName: 'Doe',
      email: 'jane.doe@example.com',
      phone: '+1-555-0102',
      dateOfBirth: '1990-07-22',
      ssn: '***-**-5678',
      kycStatus: 'VERIFIED',
      kycVerifiedAt: '2023-06-01T14:30:00Z',
      riskLevel: 'LOW',
      riskScore: 12,
      isPEP: false,
      address: {
        street: '456 Oak Avenue',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90001',
        country: 'US',
      },
      occupation: 'Marketing Manager',
      annualIncome: 95000,
      sourceOfFunds: 'EMPLOYMENT',
      accountOpenDate: '2023-06-01',
      accountAgeDays: 180,
    },
    createdAt: '2023-06-01T14:30:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ent_cust_pep_001',
    type: 'Customer',
    data: {
      customerId: 'cust_pep_001',
      customerType: 'INDIVIDUAL',
      firstName: 'Maria',
      lastName: 'Garcia',
      title: 'Ambassador',
      email: 'maria.garcia@embassy.gov',
      phone: '+1-555-0200',
      dateOfBirth: '1970-11-08',
      kycStatus: 'VERIFIED',
      kycVerifiedAt: '2023-03-15T09:00:00Z',
      riskLevel: 'HIGH',
      riskScore: 75,
      isPEP: true,
      pepType: 'FOREIGN_DIPLOMAT',
      pepPosition: 'Ambassador to the United States',
      pepCountry: 'ES',
      pepSince: '2020-01-01',
      address: {
        street: '789 Embassy Row',
        city: 'Washington',
        state: 'DC',
        zip: '20008',
        country: 'US',
      },
      sourceOfFunds: 'GOVERNMENT_SALARY',
      eddCompleted: true,
      eddCompletedAt: '2023-03-20T10:00:00Z',
      accountOpenDate: '2023-03-15',
    },
    createdAt: '2023-03-15T09:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ent_cust_military_001',
    type: 'Customer',
    data: {
      customerId: 'cust_military_001',
      customerType: 'INDIVIDUAL',
      firstName: 'James',
      lastName: 'Miller',
      rank: 'Sergeant',
      email: 'james.miller@army.mil',
      phone: '+1-555-0300',
      dateOfBirth: '1992-05-20',
      kycStatus: 'VERIFIED',
      kycVerifiedAt: '2023-08-01T11:00:00Z',
      riskLevel: 'LOW',
      riskScore: 10,
      isPEP: false,
      isMilitary: true,
      militaryBranch: 'ARMY',
      militaryStatus: 'ACTIVE_DUTY',
      militaryIdVerified: true,
      address: {
        street: 'Building 100, Fort Bragg',
        city: 'Fayetteville',
        state: 'NC',
        zip: '28307',
        country: 'US',
      },
      sourceOfFunds: 'MILITARY_SALARY',
      accountOpenDate: '2023-08-01',
    },
    createdAt: '2023-08-01T11:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ent_cust_unverified',
    type: 'Customer',
    data: {
      customerId: 'cust_unverified',
      customerType: 'INDIVIDUAL',
      firstName: 'Pending',
      lastName: 'Verification',
      email: 'pending@example.com',
      phone: '+1-555-0400',
      kycStatus: 'PENDING',
      kycSubmittedAt: '2024-01-15T10:00:00Z',
      riskLevel: 'UNKNOWN',
      isPEP: false,
      documentsSubmitted: ['ID_FRONT', 'ID_BACK'],
      documentsPending: ['PROOF_OF_ADDRESS', 'SELFIE'],
      accountOpenDate: '2024-01-15',
    },
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
];

/**
 * Business customers
 */
export const businessCustomers: ArkaEntity[] = [
  {
    id: 'ent_biz_001',
    type: 'Customer',
    data: {
      customerId: 'biz_001',
      customerType: 'BUSINESS',
      businessName: 'Tech Imports LLC',
      legalName: 'Tech Imports Limited Liability Company',
      dba: 'TechImports',
      ein: '12-3456789',
      businessType: 'IMPORT_EXPORT',
      industryCode: '423430',
      yearEstablished: 2015,
      email: 'compliance@techimports.com',
      phone: '+1-555-1000',
      kycStatus: 'VERIFIED',
      kycVerifiedAt: '2023-02-01T10:00:00Z',
      riskLevel: 'MEDIUM',
      riskScore: 45,
      isPEP: false,
      address: {
        street: '100 Commerce Drive',
        city: 'Newark',
        state: 'NJ',
        zip: '07102',
        country: 'US',
      },
      incorporationState: 'DE',
      incorporationCountry: 'US',
      annualRevenue: 5000000,
      employeeCount: 25,
      operatingCountries: ['US', 'CN', 'TW', 'JP'],
      beneficialOwners: [
        { name: 'Alice Wang', ownership: 60, verified: true },
        { name: 'Bob Chen', ownership: 40, verified: true },
      ],
      accountOpenDate: '2023-02-01',
    },
    createdAt: '2023-02-01T10:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ent_biz_msb',
    type: 'Customer',
    data: {
      customerId: 'biz_msb_001',
      customerType: 'BUSINESS',
      businessName: 'Quick Money Services',
      legalName: 'Quick Money Services Inc.',
      ein: '98-7654321',
      businessType: 'MSB',
      msbLicense: 'MSB-2023-00001',
      msbLicenseState: 'NY',
      industryCode: '522390',
      yearEstablished: 2020,
      email: 'compliance@quickmoney.com',
      phone: '+1-555-2000',
      kycStatus: 'VERIFIED',
      kycVerifiedAt: '2023-05-01T10:00:00Z',
      riskLevel: 'HIGH',
      riskScore: 70,
      isPEP: false,
      address: {
        street: '200 Financial Plaza',
        city: 'New York',
        state: 'NY',
        zip: '10001',
        country: 'US',
      },
      incorporationState: 'NY',
      incorporationCountry: 'US',
      annualRevenue: 10000000,
      transactionVolume: 50000000,
      employeeCount: 50,
      eddCompleted: true,
      eddCompletedAt: '2023-05-15T10:00:00Z',
      monitoringLevel: 'ENHANCED',
      accountOpenDate: '2023-05-01',
    },
    createdAt: '2023-05-01T10:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

/**
 * All demo customers
 */
export const allDemoCustomers: ArkaEntity[] = [
  ...individualCustomers,
  ...businessCustomers,
];

/**
 * Customer profiles for specific demo scenarios
 */
export const customerProfiles = {
  standard: {
    name: 'Standard Individual',
    description: 'Verified low-risk individual customer',
    customer: individualCustomers[0],
  },
  pep: {
    name: 'Politically Exposed Person',
    description: 'Foreign diplomat requiring enhanced due diligence',
    customer: individualCustomers.find((c) => c.data.isPEP),
  },
  military: {
    name: 'Military Servicemember',
    description: 'Active duty military with MLA protections',
    customer: individualCustomers.find((c) => c.data.isMilitary),
  },
  unverified: {
    name: 'Unverified Customer',
    description: 'Customer with pending KYC verification',
    customer: individualCustomers.find((c) => c.data.kycStatus === 'PENDING'),
  },
  business: {
    name: 'Business Customer',
    description: 'Standard verified business entity',
    customer: businessCustomers[0],
  },
  highRiskBusiness: {
    name: 'High-Risk Business',
    description: 'Money Services Business with enhanced monitoring',
    customer: businessCustomers.find((c) => c.data.businessType === 'MSB'),
  },
};
