/**
 * ARKA AI Types
 *
 * Types for AI gateway, Cortex proposals, and simulation results.
 */

import type { ArkaDecision } from './decision.js';
import type { ArkaEvent } from './event.js';
import type { ArkaRule } from './rule.js';

/**
 * Status of an AI-generated proposal
 */
export type ProposalStatus = 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED';

/**
 * Type of AI proposal
 */
export type ProposalType = 'NEW_RULE' | 'RULE_UPDATE' | 'THRESHOLD_ADJUSTMENT' | 'ANOMALY_DETECTION';

/**
 * AI-generated rule proposal
 */
export interface AIRuleProposal {
  /** Unique identifier for the proposal */
  id: string;

  /** Type of proposal */
  type: ProposalType;

  /** Current status */
  status: ProposalStatus;

  /** The proposed rule or rule changes */
  proposedRule: ArkaRule;

  /** Original rule ID if this is an update */
  originalRuleId?: string | null;

  /** AI-generated explanation of the proposal */
  explanation: string;

  /** AI-generated test cases */
  testCases: AITestCase[];

  /** Confidence score (0-1) */
  confidence: number;

  /** Source of the proposal */
  createdBy: 'AI_CORTEX' | 'HUMAN';

  /** ISO timestamp when the proposal was created */
  createdAt: string;

  /** User who approved/rejected the proposal */
  reviewedBy?: string | null;

  /** ISO timestamp when the proposal was reviewed */
  reviewedAt?: string | null;

  /** Review notes */
  reviewNotes?: string | null;

  /** Additional metadata */
  metadata: Record<string, unknown>;
}

/**
 * Test case generated by AI for rule validation
 */
export interface AITestCase {
  /** Description of the test case */
  description: string;

  /** Input event for the test */
  input: ArkaEvent;

  /** Expected decision status */
  expectedResult: 'PASS' | 'FAIL';

  /** Expected decision details */
  expectedDecision?: string;
}

/**
 * Input for natural language to rule DSL conversion
 */
export interface NLToRuleInput {
  /** Natural language description of the rule */
  description: string;

  /** Example events to help with context */
  examples?: ArkaEvent[];

  /** Constraints or additional requirements */
  constraints?: Record<string, unknown>;

  /** Target jurisdiction */
  jurisdiction?: string;

  /** Target entity type */
  entityType?: string;
}

/**
 * Output from natural language to rule DSL conversion
 */
export interface NLToRuleOutput {
  /** Generated rule in ARKA DSL format */
  ruleDsl: ArkaRule;

  /** Generated test cases */
  tests: AITestCase[];

  /** Explanation of the generated rule */
  explanation: string;

  /** Confidence score (0-1) */
  confidence: number;

  /** Any warnings or caveats */
  warnings?: string[];
}

/**
 * Input for risk pattern analysis
 */
export interface RiskAnalysisInput {
  /** Events to analyze */
  events: ArkaEvent[];

  /** Decisions made for these events */
  decisions: ArkaDecision[];

  /** Optional outcome labels (e.g., defaulted, flagged) */
  outcomeLabels?: Record<string, string>;

  /** Time window for analysis */
  timeWindow?: {
    start: string;
    end: string;
  };
}

/**
 * Risk pattern identified by AI
 */
export interface RiskPattern {
  /** Pattern identifier */
  id: string;

  /** Description of the pattern */
  description: string;

  /** Fields involved in the pattern */
  fields: string[];

  /** Risk score (0-1) */
  riskScore: number;

  /** Number of occurrences found */
  occurrences: number;

  /** Example event IDs exhibiting this pattern */
  exampleEventIds: string[];
}

/**
 * Output from risk pattern analysis
 */
export interface RiskAnalysisOutput {
  /** Identified risk patterns */
  patterns: RiskPattern[];

  /** Recommended rule changes */
  recommendations: ThresholdRecommendation[];

  /** Summary statistics */
  summary: {
    totalEventsAnalyzed: number;
    totalDecisionsAnalyzed: number;
    patternsIdentified: number;
    overallRiskScore: number;
  };

  /** AI-generated narrative summary */
  narrativeSummary: string;
}

/**
 * Threshold adjustment recommendation
 */
export interface ThresholdRecommendation {
  /** Rule ID to adjust */
  ruleId?: string;

  /** Field to adjust */
  field: string;

  /** Current threshold value */
  currentValue: unknown;

  /** Recommended new value */
  recommendedValue: unknown;

  /** Rationale for the change */
  rationale: string;

  /** Expected impact description */
  expectedImpact: string;

  /** Confidence score (0-1) */
  confidence: number;
}

/**
 * Input for legal text diff analysis
 */
export interface LegalDiffInput {
  /** Previous version of the legal text */
  oldText: string;

  /** New version of the legal text */
  newText: string;

  /** Jurisdiction code */
  jurisdiction?: string;

  /** Related entity types */
  entityTypes?: string[];
}

/**
 * Proposed rule change from legal diff
 */
export interface ProposedRuleChange {
  /** Action to take */
  action: 'CREATE' | 'UPDATE' | 'DELETE';

  /** Rule to create or update */
  rule?: ArkaRule;

  /** Rule ID to update or delete */
  existingRuleId?: string;

  /** Explanation of why this change is needed */
  explanation: string;

  /** Relevant text from the legal document */
  sourceText: string;

  /** Confidence score (0-1) */
  confidence: number;
}

/**
 * Output from legal diff analysis
 */
export interface LegalDiffOutput {
  /** Proposed rule changes */
  proposedChanges: ProposedRuleChange[];

  /** Summary of changes */
  changeSummary: string;

  /** Sections of text that couldn't be processed */
  unprocessedSections?: string[];
}

/**
 * Input for decision explanation
 */
export interface ExplainDecisionInput {
  /** The decision to explain */
  decision: ArkaDecision;

  /** The audit record for context */
  audit: Record<string, unknown>;

  /** Target audience (technical, business, legal) */
  audience?: 'technical' | 'business' | 'legal';
}

/**
 * Output from decision explanation
 */
export interface ExplainDecisionOutput {
  /** Plain language explanation */
  explanation: string;

  /** Key factors that influenced the decision */
  keyFactors: string[];

  /** Recommendations for achieving a different outcome */
  recommendations?: string[];
}

/**
 * Simulation input
 */
export interface SimulationInput {
  /** Proposed rules to simulate */
  proposedRules: ArkaRule[];

  /** Time window for historical data */
  timeWindow?: {
    start: string;
    end: string;
  };

  /** Maximum number of events to process */
  maxEvents?: number;

  /** Whether to compare against current rules */
  compareAgainstCurrent?: boolean;
}

/**
 * Simulation result
 */
export interface SimulationResult {
  /** Unique identifier for the simulation */
  id: string;

  /** Input rules that were simulated */
  inputRules: ArkaRule[];

  /** Time window used */
  timeWindow: {
    start: string;
    end: string;
  };

  /** Number of events processed */
  eventsProcessed: number;

  /** Results with current rules */
  currentResults?: {
    allowed: number;
    denied: number;
    flagged: number;
  };

  /** Results with proposed rules */
  proposedResults: {
    allowed: number;
    denied: number;
    flagged: number;
  };

  /** Impact analysis */
  impact: {
    allowedDelta: number;
    deniedDelta: number;
    flaggedDelta: number;
    percentageChange: number;
  };

  /** AI-generated summary */
  summary: string;

  /** Detailed breakdown by rule */
  ruleBreakdown: Record<string, {
    matched: number;
    passed: number;
    failed: number;
  }>;

  /** ISO timestamp when simulation was run */
  createdAt: string;

  /** Related proposal ID if applicable */
  proposalId?: string;
}

/**
 * Legal source document
 */
export interface LegalSource {
  /** Unique identifier */
  id: string;

  /** Name of the source (e.g., "California Consumer Protection Act") */
  name: string;

  /** Jurisdiction code */
  jurisdiction: string;

  /** Full text content */
  text: string;

  /** Version identifier */
  version: string;

  /** ISO timestamp when the source was ingested */
  ingestedAt: string;

  /** Previous version ID for diff tracking */
  previousVersionId?: string;

  /** Additional metadata */
  metadata: Record<string, unknown>;
}

// ============================================================================
// ARKA AI Layer Types
// ============================================================================

/**
 * Unique identifier for ARKA entities (string alias for type safety)
 */
export type ArkaEntityId = string;

/**
 * Risk score produced by the Predictive Risk Engine (PPRE)
 *
 * Represents a quantified risk assessment for any ARKA entity.
 * Used by the AI layer to score loans, accounts, customers, devices, etc.
 */
export interface RiskScore {
  /** Unique identifier for this risk score */
  id: string;

  /** ID of the entity being scored */
  entityId: ArkaEntityId;

  /** Type of entity (e.g., "Loan", "Customer", "Account") */
  entityType: string;

  /** Risk score from 0 (lowest risk) to 1 (highest risk) */
  score: number;

  /** Human-readable reasons explaining the score */
  reasons: string[];

  /** Optional labels for categorization (e.g., "high-risk", "fraud-suspect") */
  labels?: string[];

  /** Confidence level of the score (0-1) */
  confidence: number;

  /** Model or algorithm version that produced this score */
  modelVersion: string;

  /** ISO timestamp when the score was computed */
  createdAt: string;

  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Severity levels for anomaly signals
 */
export type AnomalySeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * Type of anomaly detected
 */
export type AnomalyType =
  | 'UNUSUAL_PATTERN'
  | 'THRESHOLD_BREACH'
  | 'VELOCITY_SPIKE'
  | 'BEHAVIORAL_DEVIATION'
  | 'STATISTICAL_OUTLIER'
  | 'RULE_CONFLICT'
  | 'DATA_QUALITY';

/**
 * Signal produced when an anomaly is detected in the event stream
 *
 * Used by the AI Monitor to flag unusual patterns, threshold breaches,
 * or behavioral deviations that warrant human attention.
 */
export interface AnomalySignal {
  /** Unique identifier for this signal */
  id: string;

  /** Type of anomaly detected */
  type: AnomalyType;

  /** Severity level */
  severity: AnomalySeverity;

  /** Human-readable description of the anomaly */
  description: string;

  /** IDs of events that triggered this signal */
  triggeringEventIds: string[];

  /** Entity ID if the anomaly is entity-specific */
  entityId?: ArkaEntityId;

  /** Entity type if the anomaly is entity-specific */
  entityType?: string;

  /** Anomaly score (0-1, higher = more anomalous) */
  anomalyScore: number;

  /** Baseline value for comparison (if applicable) */
  baseline?: number;

  /** Observed value that triggered the anomaly */
  observedValue?: number;

  /** Recommended actions */
  recommendations?: string[];

  /** ISO timestamp when the anomaly was detected */
  detectedAt: string;

  /** Additional context */
  context?: Record<string, unknown>;
}

/**
 * Risk impact levels for remediation suggestions
 */
export type RiskImpact = 'LOW' | 'MEDIUM' | 'HIGH';

/**
 * Suggestion produced by the AI Remediation Engine
 *
 * Represents a safe, policy-constrained action to fix an issue.
 * Always designed for human "Approve / Reject" workflows.
 */
export interface RemediationSuggestion {
  /** Unique identifier for this suggestion */
  id: string;

  /** Short title describing the action */
  title: string;

  /** Detailed description of what the action will do */
  description: string;

  /** Expected impact on risk level */
  riskImpact: RiskImpact;

  /** Whether human approval is required before execution */
  requiresApproval: boolean;

  /** Confidence in this suggestion (0-1) */
  confidence: number;

  /** Estimated effectiveness (0-1) */
  estimatedEffectiveness: number;

  /** Prerequisites that must be met */
  prerequisites?: string[];

  /** Potential side effects to consider */
  sideEffects?: string[];

  /** ISO timestamp when the suggestion was generated */
  createdAt: string;

  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Summary of an incident for AI-Aware Mode
 *
 * Generated by the AI Monitor when multiple related anomalies
 * are detected and need to be reported as a cohesive incident.
 */
export interface IncidentSummary {
  /** Unique identifier for this incident */
  id: string;

  /** Short title for the incident */
  title: string;

  /** Detailed AI-generated narrative of what happened */
  narrative: string;

  /** Severity level of the incident */
  severity: AnomalySeverity;

  /** Anomaly signals that are part of this incident */
  relatedSignals: AnomalySignal[];

  /** Affected entity IDs */
  affectedEntities: ArkaEntityId[];

  /** Suggested remediation actions */
  suggestedActions: RemediationSuggestion[];

  /** Current status of the incident */
  status: 'OPEN' | 'INVESTIGATING' | 'RESOLVED' | 'DISMISSED';

  /** ISO timestamp when the incident was created */
  createdAt: string;

  /** ISO timestamp when the incident was last updated */
  updatedAt: string;

  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

// ============================================================================
// AI Core Configuration Types
// ============================================================================

/**
 * Supported AI model providers
 */
export type AIModelProvider = 'OPENAI' | 'ANTHROPIC' | 'BEDROCK' | 'OPENROUTER' | 'LOCAL';

/**
 * Configuration for AI model calls
 */
export interface AIModelConfig {
  /** Provider to use */
  provider: AIModelProvider;

  /** Model identifier (e.g., "gpt-4", "claude-3-opus") */
  model: string;

  /** Temperature for generation (0-2, default 0.7) */
  temperature?: number;

  /** Maximum tokens to generate */
  maxTokens?: number;

  /** Timeout in milliseconds */
  timeoutMs?: number;

  /** Number of retries on failure */
  retries?: number;

  /** Additional provider-specific options */
  options?: Record<string, unknown>;
}

/**
 * Input validation result from AI guardrails
 */
export interface GuardrailValidationResult {
  /** Whether the input passed validation */
  valid: boolean;

  /** Validation errors if any */
  errors?: string[];

  /** Warnings that don't block processing */
  warnings?: string[];

  /** Sanitized input if modifications were made */
  sanitizedInput?: unknown;
}

/**
 * Output validation schema for AI responses
 */
export interface AIOutputSchema {
  /** JSON schema for expected output structure */
  schema: Record<string, unknown>;

  /** Whether to strictly enforce the schema */
  strict?: boolean;

  /** Fallback value if validation fails */
  fallback?: unknown;
}

// ============================================================================
// AI Risk Engine Types
// ============================================================================

/**
 * Input for scoring a single entity
 */
export interface RiskEngineInput {
  /** Entity ID to score */
  entityId: ArkaEntityId;

  /** Type of entity */
  entityType: string;

  /** Entity data for scoring */
  entityData: Record<string, unknown>;

  /** Recent events related to this entity */
  recentEvents?: ArkaEvent[];

  /** Recent decisions related to this entity */
  recentDecisions?: ArkaDecision[];

  /** Additional context for scoring */
  context?: Record<string, unknown>;
}

/**
 * Input for batch scoring multiple entities
 */
export interface RiskEngineBatchInput {
  /** Array of entities to score */
  entities: RiskEngineInput[];

  /** Whether to process in parallel */
  parallel?: boolean;

  /** Maximum concurrency for parallel processing */
  maxConcurrency?: number;
}

// ============================================================================
// AI Copilot Types
// ============================================================================

/**
 * Request to explain a decision
 */
export interface DecisionExplanationRequest {
  /** The decision to explain */
  decision: ArkaDecision;

  /** Related events for context */
  relatedEvents: ArkaEvent[];

  /** Target audience for the explanation */
  audience?: 'technical' | 'business' | 'legal';

  /** Specific aspects to focus on */
  focusAreas?: string[];
}

/**
 * Response with decision explanation
 */
export interface DecisionExplanationResponse {
  /** Plain language summary of the decision */
  summary: string;

  /** Key factors that influenced the decision */
  keyFactors: string[];

  /** Associated risk score if available */
  riskScore?: RiskScore;

  /** Regulatory citations if applicable */
  citations?: string[];

  /** Recommendations for different outcome */
  recommendations?: string[];
}

/**
 * Input for suggesting rule changes
 */
export interface RuleChangeSuggestionInput {
  /** Current rule to improve */
  currentRule?: import('./rule.js').ArkaRule;

  /** Description of desired behavior */
  desiredBehavior: string;

  /** Example events to consider */
  exampleEvents?: ArkaEvent[];

  /** Example decisions for context */
  exampleDecisions?: ArkaDecision[];

  /** Constraints to respect */
  constraints?: string[];
}

/**
 * Output with rule change suggestions
 */
export interface RuleChangeSuggestionOutput {
  /** Suggested rule changes */
  suggestions: Array<{
    /** Type of change */
    changeType: 'CREATE' | 'UPDATE' | 'DELETE';

    /** The suggested rule */
    rule: import('./rule.js').ArkaRule;

    /** Explanation of the change */
    explanation: string;

    /** Expected impact */
    impact: string;

    /** Confidence score */
    confidence: number;
  }>;

  /** Overall summary */
  summary: string;

  /** Warnings or caveats */
  warnings?: string[];
}

// ============================================================================
// AI Remediation Types
// ============================================================================

/**
 * Context for generating remediation suggestions
 */
export interface RemediationContext {
  /** The incident or anomaly to address */
  incident: AnomalySignal | IncidentSummary;

  /** Recent events leading up to the incident */
  recentEvents: ArkaEvent[];

  /** Current decisions in effect */
  currentDecisions: ArkaDecision[];

  /** Entity data if entity-specific */
  entityData?: Record<string, unknown>;

  /** Policy constraints to respect */
  policyConstraints?: string[];
}
